// ============================================================================
// prisma/seed.ts — Idempotent CareNexus demo seed (Mumbai, real hospital data)
//
// Consumes the curated, deterministic dataset in ./demo-data.json (generated by
// seed-data/build-demo-data.mjs from the REAL Mumbai hospital spreadsheet).
//
// Idempotency: every entity is written via upsert on a natural unique key
//   tenant   → domain
//   role     → (system role, tenantId=null, name)
//   area     → (tenantId, name)
//   clinic   → (areaId, name)
//   program  → (tenantId, activationCode)
//   user     → email
//   patient  → (tenantId, nhsNumber)
//   clinic assignment   → (userId, clinicId)
//   doctor↔patient      → first active (patientId, doctorId) or create
// No IDs are hardcoded — all primary keys come from Prisma @default(uuid()).
// Running the seed any number of times converges to the same state.
//
// Run:  pnpm --filter @workspace/api-server exec tsx prisma/seed.ts
// ============================================================================
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { readFileSync } from "node:fs";

const prisma = new PrismaClient();

type Clinic = { area: string; name: string; address?: string };
type DemoData = {
  meta: { passwordPlain: string };
  tenants: Array<{
    name: string; domain: string; city: string;
    areas: string[];
    clinics: Clinic[];
    programs: Array<{ name: string; tags: string[]; activationCode: string; priority: number }>;
    users: Array<{ role: string; firstName: string; lastName: string; email: string; mobile: string; gender: string; clinics: Clinic[] }>;
    patients: Array<{
      firstName: string; lastName: string; nhsNumber: string; email: string; mobile: string;
      gender: string; dob: string; status: string; patientGroup: string; userType: string;
      area: string; clinic: string; program: string; doctorEmail: string;
    }>;
  }>;
};

const demo = JSON.parse(readFileSync(new URL("./demo-data.json", import.meta.url), "utf8")) as DemoData;

const ckey = (area: string, name: string) => `${area}::${name}`;

async function ensureSystemRoles() {
  const names = ["SUPER_ADMIN", "AREA_ADMIN", "CLINIC_ADMIN", "DOCTOR", "OPERATOR", "STAFF"];
  const roles: Record<string, { id: string }> = {};
  for (const name of names) {
    let role = await prisma.role.findFirst({ where: { name, tenantId: null } });
    if (!role) {
      role = await prisma.role.create({ data: { tenantId: null, name, description: `${name} system role`, isSystem: true } });
    }
    roles[name] = role;
  }
  return roles;
}

async function upsertUser(opts: {
  email: string; firstName: string; lastName: string; mobile: string;
  tenantId: string; roleId: string; gender?: string; passwordHash: string;
}) {
  return prisma.user.upsert({
    where: { email: opts.email },
    update: { tenantId: opts.tenantId, roleId: opts.roleId, firstName: opts.firstName, lastName: opts.lastName, mobile: opts.mobile },
    create: {
      email: opts.email, firstName: opts.firstName, lastName: opts.lastName, mobile: opts.mobile,
      tenantId: opts.tenantId, roleId: opts.roleId, password: opts.passwordHash,
      status: "ACTIVE", emailVerified: true,
    },
  });
}

async function assignClinic(userId: string, clinicId: string) {
  await prisma.userClinicAssignment.upsert({
    where: { userId_clinicId: { userId, clinicId } },
    update: { deletedAt: null },
    create: { userId, clinicId },
  });
}

async function main() {
  console.log("🌱 Seeding CareNexus demo data (Mumbai, real hospital network)…");
  const roles = await ensureSystemRoles();
  const passwordHash = await bcrypt.hash(demo.meta.passwordPlain, 12);

  const counts: Record<string, number> = {
    tenants: 0, areas: 0, clinics: 0, programs: 0, users: 0, doctors: 0, operators: 0, staff: 0, admins: 0,
    patients: 0, assignments: 0, outcomeMetrics: 0, appointments: 0, consultations: 0, outcomes: 0,
    tasks: 0, enrollments: 0, notifications: 0, auditLogs: 0,
  };
  const rid = (n: number) => Math.floor(Math.random() * n);
  const DAY = 86400000;
  const METRIC_CATALOG = [
    { code: "HBA1C", name: "HbA1c", category: "Diabetes", unit: "%" },
    { code: "SBP", name: "Systolic BP", category: "Cardiac", unit: "mmHg" },
    { code: "BMI", name: "Body Mass Index", category: "General", unit: "kg/m2" },
    { code: "PHQ9", name: "PHQ-9 Score", category: "Mental Health", unit: "score" },
    { code: "WEIGHT", name: "Weight", category: "General", unit: "kg" },
  ];

  for (const t of demo.tenants) {
    const tenant = await prisma.tenant.upsert({
      where: { domain: t.domain },
      update: { name: t.name },
      create: { name: t.name, domain: t.domain, isActive: true },
    });
    counts.tenants++;

    // Areas
    const areaId = new Map<string, string>();
    for (const name of t.areas) {
      const a = await prisma.area.upsert({
        where: { tenantId_name: { tenantId: tenant.id, name } },
        update: {},
        create: { tenantId: tenant.id, name },
      });
      areaId.set(name, a.id);
      counts.areas++;
    }

    // Clinics
    const clinicId = new Map<string, string>(); // "area::name" -> id
    for (const c of t.clinics) {
      const aId = areaId.get(c.area)!;
      const cl = await prisma.clinic.upsert({
        where: { areaId_name: { areaId: aId, name: c.name } },
        update: { address: c.address ?? null },
        create: { tenantId: tenant.id, areaId: aId, name: c.name, address: c.address ?? null },
      });
      clinicId.set(ckey(c.area, c.name), cl.id);
      counts.clinics++;
    }

    // Programs
    const programId = new Map<string, string>();
    for (const p of t.programs) {
      const pr = await prisma.program.upsert({
        where: { tenantId_activationCode: { tenantId: tenant.id, activationCode: p.activationCode } },
        update: { name: p.name, tags: p.tags, priority: p.priority },
        create: { tenantId: tenant.id, name: p.name, activationCode: p.activationCode, tags: p.tags, priority: p.priority, isActive: true },
      });
      programId.set(p.name, pr.id);
      counts.programs++;
    }

    // Users (full role spread) — each assigned to their clinic(s).
    const doctorIdByEmail = new Map<string, string>();
    const operatorIds: string[] = [];
    const staffIds: string[] = [];
    let adminId = "";
    for (const usr of t.users) {
      const roleId = roles[usr.role]?.id ?? roles.STAFF.id;
      const u = await upsertUser({ ...usr, tenantId: tenant.id, roleId, passwordHash });
      for (const c of usr.clinics) await assignClinic(u.id, clinicId.get(ckey(c.area, c.name))!);
      if (usr.role === "DOCTOR") { doctorIdByEmail.set(usr.email, u.id); counts.doctors++; }
      else if (usr.role === "OPERATOR") { operatorIds.push(u.id); counts.operators++; }
      else if (usr.role === "STAFF") { staffIds.push(u.id); counts.staff++; }
      else if (usr.role === "AREA_ADMIN" || usr.role === "CLINIC_ADMIN") { counts.admins++; if (!adminId) adminId = u.id; }
      counts.users++;
    }
    if (!adminId) adminId = doctorIdByEmail.values().next().value ?? "";

    // Patients → belong to ONE clinic (in their area) + ONE assigned doctor at that clinic
    const tenantPatients: Array<{ id: string; clinicId: string; areaId: string; programId: string; doctorId: string }> = [];
    for (const p of t.patients) {
      const aId = areaId.get(p.area)!;
      const cId = clinicId.get(ckey(p.area, p.clinic))!;
      const prId = programId.get(p.program)!;
      const docId = doctorIdByEmail.get(p.doctorEmail)!;

      const patient = await prisma.patient.upsert({
        where: { tenantId_nhsNumber: { tenantId: tenant.id, nhsNumber: p.nhsNumber } },
        update: { clinicId: cId, areaId: aId, programId: prId, status: p.status as any },
        create: {
          tenantId: tenant.id, nhsNumber: p.nhsNumber,
          firstName: p.firstName, lastName: p.lastName, email: p.email, mobile: p.mobile,
          gender: p.gender as any, dob: new Date(p.dob), status: p.status as any,
          patientGroup: p.patientGroup as any, userType: p.userType as any,
          programId: prId, clinicId: cId, areaId: aId,
          country: "India", registrationDate: new Date("2026-01-01"), createdBy: adminId || undefined,
        },
      });
      counts.patients++;
      tenantPatients.push({ id: patient.id, clinicId: cId, areaId: aId, programId: prId, doctorId: docId });

      // Doctor ↔ patient assignment (idempotent)
      const existing = await prisma.doctorPatientAssignment.findFirst({
        where: { patientId: patient.id, doctorId: docId, tenantId: tenant.id, deletedAt: null },
      });
      if (!existing) {
        await prisma.doctorPatientAssignment.create({
          data: { tenantId: tenant.id, patientId: patient.id, doctorId: docId, clinicId: cId, areaId: aId },
        });
      }
      counts.assignments++;
    }

    // ── Transactional / workflow data (idempotent: generated once per tenant) ──
    const pickPt = () => tenantPatients[rid(tenantPatients.length)];
    const now = Date.now();

    // Outcome metrics (required before outcomes)
    const metricIds: string[] = [];
    for (const m of METRIC_CATALOG) {
      const om = await prisma.outcomeMetric.upsert({
        where: { tenantId_code: { tenantId: tenant.id, code: m.code } },
        update: {},
        create: { tenantId: tenant.id, ...m, isActive: true },
      });
      metricIds.push(om.id);
      counts.outcomeMetrics++;
    }

    // Appointments — top up to target with a realistic status mix. New rows skew
    // COMPLETED so there are always enough to back the consultation target.
    const APPT_TARGET = 50;
    const haveAppt = await prisma.appointment.count({ where: { tenantId: tenant.id } });
    if (haveAppt < APPT_TARGET) {
      const mix = ["COMPLETED", "COMPLETED", "COMPLETED", "SCHEDULED", "CANCELLED", "NO_SHOW"];
      const rows = Array.from({ length: APPT_TARGET - haveAppt }, (_, i) => {
        const pt = pickPt();
        const st = mix[i % mix.length];
        const offset = st === "SCHEDULED" ? (rid(20) + 1) * DAY : -((rid(60) + 1) * DAY);
        return { tenantId: tenant.id, patientId: pt.id, doctorId: pt.doctorId, clinicId: pt.clinicId, appointmentDate: new Date(now + offset), durationMinutes: 30, status: st, notes: "Demo appointment" };
      });
      await prisma.appointment.createMany({ data: rows as any });
      counts.appointments += rows.length;
    }

    // Consultations — top up to target. Reuse COMPLETED appointments not yet consulted;
    // if there aren't enough, mint a backing COMPLETED appointment for each shortfall.
    const CONS_TARGET = 26;
    const haveCons = await prisma.consultation.count({ where: { tenantId: tenant.id } });
    if (haveCons < CONS_TARGET) {
      let need = CONS_TARGET - haveCons;
      const completed = await prisma.appointment.findMany({ where: { tenantId: tenant.id, status: "COMPLETED" }, select: { id: true, patientId: true, doctorId: true, clinicId: true } });
      const used = new Set((await prisma.consultation.findMany({ where: { tenantId: tenant.id }, select: { appointmentId: true } })).map((c) => c.appointmentId));
      const backing = completed.filter((a) => !used.has(a.id));
      // Mint extra completed appointments if we don't have enough free ones.
      while (backing.length < need) {
        const pt = pickPt();
        const appt = await prisma.appointment.create({ data: { tenantId: tenant.id, patientId: pt.id, doctorId: pt.doctorId, clinicId: pt.clinicId, appointmentDate: new Date(now - (rid(60) + 1) * DAY), durationMinutes: 30, status: "COMPLETED", notes: "Demo appointment" } });
        backing.push({ id: appt.id, patientId: pt.id, doctorId: pt.doctorId, clinicId: pt.clinicId });
        counts.appointments++;
      }
      const rows = backing.slice(0, need).map((a) => ({
        tenantId: tenant.id, patientId: a.patientId, appointmentId: a.id, doctorId: a.doctorId, clinicId: a.clinicId,
        chiefComplaint: "Routine review", symptoms: "Stable", observations: "Within normal limits", diagnosis: "Chronic condition — controlled",
        treatmentPlan: "Continue current management", medications: "As prescribed", followUpInstructions: "Review in 3 months", consultationDate: new Date(now - rid(30) * DAY),
      }));
      if (rows.length) await prisma.consultation.createMany({ data: rows as any });
      counts.consultations += rows.length;
    }

    // Outcomes — improving / stable / regressing relative to target
    if ((await prisma.patientOutcome.count({ where: { tenantId: tenant.id } })) === 0) {
      const rows = Array.from({ length: 25 }, (_, i) => {
        const pt = pickPt();
        const base = 50 + rid(40);
        return { tenantId: tenant.id, patientId: pt.id, programId: pt.programId, outcomeMetricId: metricIds[i % metricIds.length], doctorId: pt.doctorId, baselineValue: base, currentValue: base + (rid(30) - 12), targetValue: base - 20, measuredAt: new Date(now - rid(60) * DAY), notes: "Demo outcome measurement" };
      });
      await prisma.patientOutcome.createMany({ data: rows as any });
      counts.outcomes += rows.length;
    }

    // Tasks — status mix, assigned across doctors / operators / staff
    if ((await prisma.careTask.count({ where: { tenantId: tenant.id } })) === 0) {
      const assignees = [...doctorIdByEmail.values(), ...operatorIds, ...staffIds].filter(Boolean);
      const statuses = ["PENDING", "IN_PROGRESS", "COMPLETED", "OVERDUE"];
      const prios = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
      const titles = ["Follow-up call", "Review lab results", "Update care plan", "Medication reconciliation", "Schedule review"];
      const rows = Array.from({ length: 25 }, (_, i) => {
        const pt = pickPt();
        const st = statuses[i % statuses.length];
        return { tenantId: tenant.id, patientId: pt.id, assignedBy: adminId, assignedTo: assignees[i % assignees.length], title: titles[i % titles.length], description: "Demo task", priority: prios[i % prios.length], status: st, dueDate: new Date(now + (st === "OVERDUE" ? -((rid(10) + 1) * DAY) : (rid(20) + 1) * DAY)), completedAt: st === "COMPLETED" ? new Date(now - rid(5) * DAY) : null };
      });
      await prisma.careTask.createMany({ data: rows as any });
      counts.tasks += rows.length;
    }

    // Program enrollments — one per patient, status mix
    if ((await prisma.programEnrollment.count({ where: { tenantId: tenant.id } })) === 0) {
      const est = ["ACTIVE", "ACTIVE", "ACTIVE", "COMPLETED", "CANCELLED"];
      const rows = tenantPatients.map((pt, i) => ({ tenantId: tenant.id, patientId: pt.id, programId: pt.programId, status: est[i % est.length], enrolledAt: new Date(now - (rid(180) + 10) * DAY), completedAt: est[i % est.length] === "COMPLETED" ? new Date(now - rid(10) * DAY) : null }));
      await prisma.programEnrollment.createMany({ data: rows as any });
      counts.enrollments += rows.length;
    }

    // Notifications — to a handful of doctors
    if ((await prisma.notification.count({ where: { tenantId: tenant.id } })) === 0) {
      const rows = [...doctorIdByEmail.values()].slice(0, 5).map((uid, i) => ({ tenantId: tenant.id, userId: uid, title: i % 2 ? "Task due soon" : "New patient assignment", message: "You have an item that needs your attention.", type: (i % 2 ? "INFO" : "WARNING"), isRead: i % 3 === 0 }));
      if (rows.length) await prisma.notification.createMany({ data: rows as any });
      counts.notifications += rows.length;
    }

    // Audit logs — sample CREATE entries
    if ((await prisma.auditLog.count({ where: { tenantId: tenant.id } })) === 0) {
      const rows = tenantPatients.slice(0, 5).map((pt) => ({ tenantId: tenant.id, entityType: "Patient", entityId: pt.id, action: "CREATE", actorId: adminId || null, afterValue: { seeded: true } }));
      if (rows.length) await prisma.auditLog.createMany({ data: rows as any });
      counts.auditLogs += rows.length;
    }

    console.log(`  ✅ ${t.name}: ${t.areas.length} areas · ${t.clinics.length} clinics · ${t.users.length} users · ${t.patients.length} patients · appts/cons/tasks/outcomes seeded`);
  }

  console.log("\n🎉 Demo seed complete:", JSON.stringify(counts));
  console.log(`🔐 Demo login password for all generated users: ${demo.meta.passwordPlain}`);
  console.log(`   e.g. admin@${demo.tenants[0].domain}`);
}

main()
  .catch((e) => { console.error("❌ Seed failed:", e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
